# Dockerfile for shard_layer

# Dockerfile for k8s_server
FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .
RUN cd /app/src && go mod tidy
RUN cd /app/src/main/shard && go build -o ../../../shard_layer shard_layer.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/shard_layer .
EXPOSE 8080
ENTRYPOINT ["./shard_layer"]