# Dockerfile for k8s_server
FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .
RUN cd /app/src && go mod tidy
RUN cd /app/src/main/server && go build -o ../../../k8s_server k8s_server.go config.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/k8s_server .
EXPOSE 8080
ENTRYPOINT ["./k8s_server"]